# Generated by Django 4.2.7 on 2024-03-13 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0013_alter_cartitem_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('grains_rice', 'Grains & Rice'), ('food_cupboard', 'Food Cupboard')], default='None', max_length=20),
        ),
    ]
