# Generated by Django 4.2.7 on 2024-03-18 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0014_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('grains_rice', 'Grains & Rice'), ('food_cupboard', 'Food Cupboard'), ('household_care', 'Household Care')], default='None', max_length=20),
        ),
    ]
