# Generated by Django 4.2.7 on 2024-03-18 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0016_alter_product_old_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('grains_rice', 'Grains & Rice'), ('food_cupboard', 'Food Cupboard'), ('household_care', 'Household Care'), ('laundry', 'Laundry')], default='None', max_length=20),
        ),
    ]
