# Generated by Django 4.2.7 on 2024-03-29 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0019_category_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='category',
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('grains_rice', 'Grains & Rice'), ('food_cupboard', 'Food Cupboard'), ('household_care', 'Household Care'), ('laundry', 'Laundry'), ('fragrances', 'Fragrances'), ('air_conditioner', 'Air Conditioner')], default='None', max_length=20),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Item',
        ),
    ]
