# Generated by Django 4.2.7 on 2024-04-17 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0024_paymentevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('pay_on_delivery', 'Tap & Relax, Pay with Bank Transfer on Delivery'), ('bank_transfer', 'Bank Transfer')], default='pay_on_delivery', max_length=20),
        ),
    ]
