# Generated by Django 4.2.7 on 2024-04-21 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0028_category_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useractivity',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_activities', to='ecommerce.product'),
        ),
    ]
