# Generated by Django 4.2.7 on 2024-04-25 12:31

from django.db import migrations
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0035_remove_product_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='supercategory',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(default='Quality product', verbose_name='Text'),
        ),
    ]
