# Generated by Django 4.2.7 on 2024-01-21 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_customuser_options_alter_customuser_managers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='personaldetails',
            name='security_code',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
