# Generated by Django 4.2.7 on 2024-01-31 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_personaldetails_security_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='personaldetails',
            name='middle_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
