# Generated by Django 4.2.7 on 2024-04-09 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_personaldetails_security_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='personaldetails',
            name='security_code_expiration',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
